### ISSUE TITLE
[BUG] CodeSpace Pub Url Error

### ISSUE THREAD

**Issue by Miamoto-Musashi** [cheshire-cat-ai/core#333]
**Describe the bug**
after codespace launch the console show an url to follow but the public url does not work, other url seems working

**To Reproduce**
1. launch codespace env
2. docker-compose up
3. follow public url

**Expected behavior**
the page opens with woirkng cat

**Actual behavior**
The page shows an error "Something went wrong while connecting to the server. Please try again later" which doesn't make much sense, imo, if I retry later is still in error

**Additional context**
first time launch
no api key or other settings provided
api url & admin URL are working 

the error in the console is

```bash
INFO:     172.18.0.1:57044 - "GET /settings/prompt HTTP/1.1" 500 Internal Server Error
cheshire_cat_core             | ERROR:    Exception in ASGI application
cheshire_cat_core             | Traceback (most recent call last):
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1800, in _execute_context
cheshire_cat_core             |     context = constructor(
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1076, in _init_compiled
cheshire_cat_core             |     param = [
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in <listcomp>
cheshire_cat_core             |     processors[key](compiled_params[key])
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1660, in process
cheshire_cat_core             |     return process_param(value, dialect)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/fastapi_utils/guid_type.py", line 50, in process_bind_param
cheshire_cat_core             |     return "%.32x" % uuid.UUID(value).int
cheshire_cat_core             |   File "/usr/local/lib/python3.10/uuid.py", line 177, in __init__
cheshire_cat_core             |     raise ValueError('badly formed hexadecimal UUID string')
cheshire_cat_core             | ValueError: badly formed hexadecimal UUID string
cheshire_cat_core             | 
cheshire_cat_core             | The above exception was the direct cause of the following exception:
cheshire_cat_core             | 
cheshire_cat_core             | Traceback (most recent call last):
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
cheshire_cat_core             |     result = await app(  # type: ignore[func-returns-value]
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
cheshire_cat_core             |     return await self.app(scope, receive, send)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 274, in __call__
cheshire_cat_core             |     await super().__call__(scope, receive, send)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
cheshire_cat_core             |     await self.middleware_stack(scope, receive, send)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
cheshire_cat_core             |     raise exc
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
cheshire_cat_core             |     await self.app(scope, receive, _send)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
cheshire_cat_core             |     await self.app(scope, receive, send)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
cheshire_cat_core             |     raise exc
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
cheshire_cat_core             |     await self.app(scope, receive, sender)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
cheshire_cat_core             |     raise e
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
cheshire_cat_core             |     await self.app(scope, receive, send)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
cheshire_cat_core             |     await route.handle(scope, receive, send)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
cheshire_cat_core             |     await self.app(scope, receive, send)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
cheshire_cat_core             |     response = await func(request)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 238, in app
cheshire_cat_core             |     raw_response = await run_endpoint_function(
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 166, in run_endpoint_function
cheshire_cat_core             |     return await run_in_threadpool(dependant.call, **values)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
cheshire_cat_core             |     return await anyio.to_thread.run_sync(func, *args)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
cheshire_cat_core             |     return await get_asynclib().run_sync_in_worker_thread(
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
cheshire_cat_core             |     return await future
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
cheshire_cat_core             |     result = context.run(func, *args)
cheshire_cat_core             |   File "/app/./cat/routes/setting/general_setting.py", line 51, in get_setting
cheshire_cat_core             |     setting = setting_query.first()
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2823, in first
cheshire_cat_core             |     return self.limit(1)._iter().first()
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
cheshire_cat_core             |     result = self.session.execute(
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlmodel/orm/session.py", line 101, in execute
cheshire_cat_core             |     return super().execute(  # type: ignore
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
cheshire_cat_core             |     result = conn._execute_20(statement, params or {}, execution_options)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
cheshire_cat_core             |     return meth(self, args_10style, kwargs_10style, execution_options)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
cheshire_cat_core             |     return connection._execute_clauseelement(
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
cheshire_cat_core             |     ret = self._execute_context(
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1806, in _execute_context
cheshire_cat_core             |     self._handle_dbapi_exception(
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
cheshire_cat_core             |     util.raise_(
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
cheshire_cat_core             |     raise exception
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1800, in _execute_context
cheshire_cat_core             |     context = constructor(
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1076, in _init_compiled
cheshire_cat_core             |     param = [
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in <listcomp>
cheshire_cat_core             |     processors[key](compiled_params[key])
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1660, in process
cheshire_cat_core             |     return process_param(value, dialect)
cheshire_cat_core             |   File "/usr/local/lib/python3.10/site-packages/fastapi_utils/guid_type.py", line 50, in process_bind_param
cheshire_cat_core             |     return "%.32x" % uuid.UUID(value).int
cheshire_cat_core             |   File "/usr/local/lib/python3.10/uuid.py", line 177, in __init__
cheshire_cat_core             |     raise ValueError('badly formed hexadecimal UUID string')
cheshire_cat_core             | sqlalchemy.exc.StatementError: (builtins.ValueError) badly formed hexadecimal UUID string
cheshire_cat_core             | [SQL: SELECT setting.setting_id AS setting_setting_id, setting.value AS setting_value, setting."createdAt" AS "setting_createdAt", setting."updatedAt" AS "setting_updatedAt", setting.name AS setting_name, setting.category AS setting_category, setting.enabled AS setting_enabled 
cheshire_cat_core             | FROM setting 
cheshire_cat_core             | WHERE setting.setting_id = ?
cheshire_cat_core             |  LIMIT ? OFFSET ?]
cheshire_cat_core             | [parameters: [{}]]
cheshire_cat_core             | INFO:     172.18.0.1:57056 - "GET /favicon.ico HTTP/1.1" 200 OK
```

thanks

**Comment by pieroit** [comment]
can you try now?

**Comment by Miamoto-Musashi** [comment]
Still same error on entry page but console doesn't show any exception

**Comment by pieroit** [comment]
Won't fix
