### ISSUE TITLE
[BUG] DumbEmbedder.__init__() got an unexpected keyword argument 'model'

### ISSUE THREAD

**Issue by danieleongari** [cheshire-cat-ai/core#440]
After plying with the choice of the Embedding in the app, things started to look buggy: 
I was checking and saving some different options for Embedding but at a certain point the button "Save" stopped being responsive.

So, I restarted the container but now I get this message:
```
cheshire_cat_core           | [2023-08-29 07:49:08.140] DEBUG  cat.mad_hatter.Plugin._load_hooks_and_tools::175 => 'Import module cat.mad_hatter.core_plugin.hooks.rabbithole'
cheshire_cat_core           | ERROR:    Traceback (most recent call last):
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
cheshire_cat_core           |     async with self.lifespan_context(app):
cheshire_cat_core           |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
cheshire_cat_core           |     return await anext(self.gen)
cheshire_cat_core           |   File "/app/cat/main.py", line 30, in lifespan
cheshire_cat_core           |     app.state.ccat = CheshireCat()
cheshire_cat_core           |   File "/app/cat/looking_glass/cheshire_cat.py", line 43, in __init__
cheshire_cat_core           |     self.load_natural_language()
cheshire_cat_core           |   File "/app/cat/looking_glass/cheshire_cat.py", line 88, in load_natural_language
cheshire_cat_core           |     self.embedder = self.mad_hatter.execute_hook("get_language_embedder")
cheshire_cat_core           |   File "/app/cat/mad_hatter/mad_hatter.py", line 248, in execute_hook
cheshire_cat_core           |     return h.function(*args, cat=self.ccat)
cheshire_cat_core           |   File "/app/cat/mad_hatter/core_plugin/hooks/models.py", line 96, in get_language_embedder
cheshire_cat_core           |     embedder = FactoryClass.get_embedder_from_config(selected_embedder_config["value"])
cheshire_cat_core           |   File "/app/cat/factory/embedder.py", line 19, in get_embedder_from_config
cheshire_cat_core           |     return cls._pyclass(**config)
cheshire_cat_core           | TypeError: DumbEmbedder.__init__() got an unexpected keyword argument 'model'
cheshire_cat_core           |
cheshire_cat_core           | ERROR:    Application startup failed. Exiting.
cheshire_cat_core           |
```

**Comment by danieleongari** [comment]
My `core/metadata.json` contains:
```
{"_default": {"1": {"name": "EmbedderOpenAIConfig", "value": {"model": ...
```
so I guess it is trying to feed OpenAI embedder into the Dumb embedder, with the problem of having somehow saved contradictory settings.

**Comment by danieleongari** [comment]
I tried to reproduce the problem:
1. I changed again the Embedder to OpenAI from DumbEmbedder
2. this takes a while ~10s
3.  If I'm impatient and I click other buttons this makes the problem

**Comment by pieroit** [comment]
Thank you for reproducing the error @danieleongari 
Which "other buttons" make the problem?

**Comment by danieleongari** [comment]
Closing the "Embeddings" side windows was the triggering action for the bug, I think.

**Comment by pieroit** [comment]
fixed by @zAlweNy26 in admin, thanks!!
