### ISSUE TITLE
[BUG] Qdrant IndexError: list index out of range

### ISSUE THREAD

**Issue by MattNot** [cheshire-cat-ai/core#459]
**Describe the bug**

Hi, tried to startup the cat but whenever the core container starts an IndexError is lifted. Logs below.

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
1. Pull the actual master branch
2. docker-compose up -d
3. See error

**Expected behavior**
Should start.

**Additional context**
Logs:

```

2023-09-18 16:12:55 INFO:     Will watch for changes in these directories: ['/app']
2023-09-18 16:12:55 INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
2023-09-18 16:12:55 INFO:     Started reloader process [1] using WatchFiles
2023-09-18 16:13:07 INFO:     Started server process [31]
2023-09-18 16:13:07 INFO:     Waiting for application startup.
2023-09-18 16:13:11 ERROR:    Traceback (most recent call last):
2023-09-18 16:13:11   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
2023-09-18 16:13:11     async with self.lifespan_context(app):
2023-09-18 16:13:11   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
2023-09-18 16:13:11     return await anext(self.gen)
2023-09-18 16:13:11   File "/app/cat/main.py", line 29, in lifespan
2023-09-18 16:13:11     app.state.ccat = CheshireCat()
2023-09-18 16:13:11   File "/app/cat/looking_glass/cheshire_cat.py", line 47, in __init__
2023-09-18 16:13:11     self.load_memory()
2023-09-18 16:13:11   File "/app/cat/looking_glass/cheshire_cat.py", line 90, in load_memory
2023-09-18 16:13:11     self.memory = LongTermMemory(vector_memory_config=vector_memory_config)
2023-09-18 16:13:11   File "/app/cat/memory/long_term_memory.py", line 17, in __init__
2023-09-18 16:13:11     self.vectors = VectorMemory(**vector_memory_config)
2023-09-18 16:13:11   File "/app/cat/memory/vector_memory.py", line 44, in __init__
2023-09-18 16:13:11     collection = VectorMemoryCollection(
2023-09-18 16:13:11   File "/app/cat/memory/vector_memory.py", line 116, in __init__
2023-09-18 16:13:11     self.check_embedding_size()
2023-09-18 16:13:11   File "/app/cat/memory/vector_memory.py", line 128, in check_embedding_size
2023-09-18 16:13:11     if alias==self.client.get_collection_aliases(self.collection_name).aliases[0].alias_name and same_size:
2023-09-18 16:13:11 IndexError: list index out of range
2023-09-18 16:13:11 
2023-09-18 16:13:11 ERROR:    Application startup failed. Exiting.

```

I'm on windows 11 with docker desktop.

**Comment by nicola-corbellini** [comment]
Try to delete the long_term_memory folder and build the container again

**Comment by MattNot** [comment]
Done, nothing changed

**Comment by MattNot** [comment]
The file cheshire-cat\long_term_memory\vector\aliases\data.json is empty

```
{}
```

**Comment by nicola-corbellini** [comment]
@MattNot have you built the container again with `docker compose builld --no-cache` or you just started it with `docker compose up -d`? 
I tried a new installation on my machine and I was not able to reproduce the bug.

**Comment by MattNot** [comment]
Yes, used --no-cache

**Comment by pieroit** [comment]
The problem is on the collection aliases array
`if alias==self.client.get_collection_aliases(self.collection_name).aliases[0].alias_name and same_size`

In your case I guess it is an empty list, but should be populated at first start.
Just tried out a fresh `main` installation and could not reproduce the error.

Could be a problem with Qdrant container on your OS

**Comment by MattNot** [comment]
Can be solved providing an example of that file/folder?

**Comment by pieroit** [comment]
@MattNot we had a call with @nicola-corbellini and there is a temp fix.
Comment this line:

https://github.com/cheshire-cat-ai/core/blob/a1262d3cf3abe7cf31cb79e8bcee7343339b6275/core/cat/memory/vector_memory.py#L133

Let us know so we can better code this part

**Comment by MattNot** [comment]
Commented that line but same error rises:

```
2023-09-20 09:46:22 INFO:     Will watch for changes in these directories: ['/app']
2023-09-20 09:46:22 INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
2023-09-20 09:46:22 INFO:     Started reloader process [1] using WatchFiles
2023-09-20 09:46:31 INFO:     Started server process [31]
2023-09-20 09:46:31 INFO:     Waiting for application startup.
2023-09-20 09:46:34 ERROR:    Traceback (most recent call last):
2023-09-20 09:46:34   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
2023-09-20 09:46:34     async with self.lifespan_context(app):
2023-09-20 09:46:34   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
2023-09-20 09:46:34     return await anext(self.gen)
2023-09-20 09:46:34   File "/app/cat/main.py", line 29, in lifespan
2023-09-20 09:46:34     app.state.ccat = CheshireCat()
2023-09-20 09:46:34   File "/app/cat/looking_glass/cheshire_cat.py", line 47, in __init__
2023-09-20 09:46:34     self.load_memory()
2023-09-20 09:46:34   File "/app/cat/looking_glass/cheshire_cat.py", line 90, in load_memory
2023-09-20 09:46:34     self.memory = LongTermMemory(vector_memory_config=vector_memory_config)
2023-09-20 09:46:34   File "/app/cat/memory/long_term_memory.py", line 17, in __init__
2023-09-20 09:46:34     self.vectors = VectorMemory(**vector_memory_config)
2023-09-20 09:46:34   File "/app/cat/memory/vector_memory.py", line 44, in __init__
2023-09-20 09:46:34     collection = VectorMemoryCollection(
2023-09-20 09:46:34   File "/app/cat/memory/vector_memory.py", line 116, in __init__
2023-09-20 09:46:34     self.check_embedding_size()
2023-09-20 09:46:34   File "/app/cat/memory/vector_memory.py", line 128, in check_embedding_size
2023-09-20 09:46:34     if alias==self.client.get_collection_aliases(self.collection_name).aliases[0].alias_name and same_size:
2023-09-20 09:46:34 IndexError: list index out of range
2023-09-20 09:46:34 
2023-09-20 09:46:34 ERROR:    Application startup failed. Exiting.

```

**Comment by pieroit** [comment]
Delete long_term_memory and metadata.json

**Comment by MattNot** [comment]
Okay guys, i dont know what's wrong with my company pc, tried on another pc and it works.
