### ISSUE TITLE
Application startup failed

### ISSUE THREAD

**Issue by Gyro0o** [cheshire-cat-ai/core#598]
When I enter the command 
''docker compose up ''
I get this error:

[+] Running 3/0
 ✔ Container cheshire_cat_vector_memory  Created                                                                   0.0s
 ✔ Container ollama_cat                  Created                                                                   0.0s
 ✔ Container cheshire_cat_core           Created                                                                   0.0s
Attaching to cheshire_cat_core, cheshire_cat_vector_memory, ollama_cat
cheshire_cat_vector_memory  |            _                 _
cheshire_cat_vector_memory  |   __ _  __| |_ __ __ _ _ __ | |_
cheshire_cat_vector_memory  |  / _` |/ _` | '__/ _` | '_ \| __|
cheshire_cat_vector_memory  | | (_| | (_| | | | (_| | | | | |_
cheshire_cat_vector_memory  |  \__, |\__,_|_|  \__,_|_| |_|\__|
cheshire_cat_vector_memory  |     |_|
cheshire_cat_vector_memory  |
cheshire_cat_vector_memory  | Access web UI at http://localhost:6333/dashboard
cheshire_cat_vector_memory  |
cheshire_cat_vector_memory  |
cheshire_cat_vector_memory  | 2023-12-01T22:36:07.430246Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json
cheshire_cat_vector_memory  | 2023-12-01T22:36:07.526603Z  INFO qdrant: Distributed mode disabled
cheshire_cat_vector_memory  | 2023-12-01T22:36:07.526645Z  INFO qdrant: Telemetry reporting enabled, id: f6f599b1-65ca-4b47-b252-4ed288a3f7f0
cheshire_cat_vector_memory  | 2023-12-01T22:36:07.529190Z  INFO qdrant::actix: TLS disabled for REST API
cheshire_cat_vector_memory  | 2023-12-01T22:36:07.529444Z  INFO qdrant::actix: Qdrant HTTP listening on 6333
cheshire_cat_vector_memory  | 2023-12-01T22:36:07.529481Z  INFO actix_server::builder: Starting 11 workers
cheshire_cat_vector_memory  | 2023-12-01T22:36:07.529498Z  INFO actix_server::server: Actix runtime found; starting in Actix runtime
cheshire_cat_vector_memory  | 2023-12-01T22:36:07.533686Z  INFO qdrant::tonic: Qdrant gRPC listening on 6334
cheshire_cat_vector_memory  | 2023-12-01T22:36:07.533731Z  INFO qdrant::tonic: TLS disabled for gRPC API
ollama_cat                  | 2023/12/01 22:36:07 images.go:784: total blobs: 0
ollama_cat                  | 2023/12/01 22:36:07 images.go:791: total unused blobs removed: 0
ollama_cat                  | 2023/12/01 22:36:07 routes.go:777: Listening on [::]:11434 (version 0.1.12)
cheshire_cat_core           | INFO:     Will watch for changes in these directories: ['/app']
cheshire_cat_core           | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
cheshire_cat_core           | INFO:     Started reloader process [7] using WatchFiles
cheshire_cat_core           | INFO:     Started server process [32]
cheshire_cat_core           | INFO:     Waiting for application startup.
cheshire_cat_core           | ERROR:    Traceback (most recent call last):
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
cheshire_cat_core           |     async with self.lifespan_context(app) as maybe_state:
cheshire_cat_core           |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
cheshire_cat_core           |     return await anext(self.gen)
cheshire_cat_core           |   File "/app/cat/main.py", line 29, in lifespan
cheshire_cat_core           |     app.state.ccat = CheshireCat()
cheshire_cat_core           |   File "/app/cat/utils.py", line 111, in getinstance
cheshire_cat_core           |     cls.instances[class_] = class_(*args, **kwargs)
cheshire_cat_core           |   File "/app/cat/looking_glass/cheshire_cat.py", line 44, in __init__
cheshire_cat_core           |     self.mad_hatter = MadHatter()
cheshire_cat_core           |   File "/app/cat/utils.py", line 111, in getinstance
cheshire_cat_core           |     cls.instances[class_] = class_(*args, **kwargs)
cheshire_cat_core           |   File "/app/cat/mad_hatter/mad_hatter.py", line 42, in __init__
cheshire_cat_core           |     self.find_plugins()
cheshire_cat_core           |   File "/app/cat/mad_hatter/mad_hatter.py", line 84, in find_plugins
cheshire_cat_core           |     self.active_plugins = self.load_active_plugins_from_db()
cheshire_cat_core           |   File "/app/cat/mad_hatter/mad_hatter.py", line 153, in load_active_plugins_from_db
cheshire_cat_core           |     active_plugins = crud.get_setting_by_name("active_plugins")
cheshire_cat_core           |   File "/app/cat/db/crud.py", line 33, in get_setting_by_name
cheshire_cat_core           |     result = get_db().search(query.name == name)
cheshire_cat_core           |   File "/app/cat/db/database.py", line 17, in get_db
cheshire_cat_core           |     return Database().db
cheshire_cat_core           |   File "/app/cat/utils.py", line 111, in getinstance
cheshire_cat_core           |     cls.instances[class_] = class_(*args, **kwargs)
cheshire_cat_core           |   File "/app/cat/db/database.py", line 10, in __init__
cheshire_cat_core           |     self.db = TinyDB(self.get_file_name())
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/tinydb/database.py", line 94, in __init__
cheshire_cat_core           |     self._storage: Storage = storage(*args, **kwargs)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/tinydb/storages.py", line 113, in __init__
cheshire_cat_core           |     touch(path, create_dirs=create_dirs)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/tinydb/storages.py", line 32, in touch
cheshire_cat_core           |     with open(path, 'a'):
cheshire_cat_core           | IsADirectoryError: [Errno 21] Is a directory: 'metadata.json'
cheshire_cat_core           |
cheshire_cat_core           | ERROR:    Application startup failed. Exiting.
cheshire_cat_core           |

**Comment by valentimarco** [comment]
can you send the docker-compose.yml file and the directory structure? 
Use markdown pls! (up-right of the text box there is the markdown menu)

**Comment by Gyro0o** [comment]
Sure here it is:

version: '3.7'

services:
  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    depends_on:
      - cheshire-cat-vector-memory
      - ollama
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - CORE_HOST=${CORE_HOST:-localhost}
      - CORE_PORT=${CORE_PORT:-1865}
      - QDRANT_HOST=${QDRANT_HOST:-cheshire_cat_vector_memory}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
      - API_KEY=${API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - DEBUG=${DEBUG:-true}
      - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
    ports:
      - ${CORE_PORT:-1865}:80
    volumes:
      - ./cat/static:/app/cat/static
      - ./cat/public:/app/cat/public
      - ./cat/plugins:/app/cat/plugins
      - ./cat/metadata.json:/app/metadata.json
    restart: unless-stopped

  cheshire-cat-vector-memory:
    image: qdrant/qdrant:latest
    container_name: cheshire_cat_vector_memory
    expose:
      - 6333
    volumes:
      - ./cat/long_term_memory/vector:/qdrant/storage
    restart: unless-stopped

  ollama:
    container_name: ollama_cat
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
    environment:
      - gpus=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

**Comment by valentimarco** [comment]
this docker-compose is from the local-cat repo... the metadata.json is ready to be copy...

**Comment by valentimarco** [comment]
can you send the directory structure? (if you are in linux, use `tree .`)

**Comment by Gyro0o** [comment]
No I'm on windows

**Comment by valentimarco** [comment]
After a search, works even in windows, try the command in powershell

**Comment by Gyro0o** [comment]
> this docker-compose is from the local-cat repo... the metadata.json is ready to be copy...

the metadata folder is empty
if that's what you mean

**Comment by valentimarco** [comment]
metadata is not a folder... this is why i am asking for the dictory structure

**Comment by Gyro0o** [comment]
> After a search, works even in windows, try the command in powershell

same result

**Comment by valentimarco** [comment]
Ok, can you do a screenshot and upload it?  (by drag and drop!)

**Comment by Gyro0o** [comment]
![Screenshot 2023-12-02 143954](https://github.com/cheshire-cat-ai/core/assets/117460296/c37f2b19-aa8e-4eea-b67e-522327b9898b)

**Comment by valentimarco** [comment]
Use the new version of the local cat repo:
https://github.com/cheshire-cat-ai/local-cat

**Comment by Gyro0o** [comment]
> Use the new version of the local cat repo: https://github.com/cheshire-cat-ai/local-cat
> 
> from now on use the discord server to ask support

same issue
