### ISSUE TITLE
[BUG] Ollama does not connect

### ISSUE THREAD

**Issue by gerroon** [cheshire-cat-ai/core#630]
**Describe the bug**

I am using it under WSL2 Win 11

Ollama running locally, I can use Ollama run to connect to this instance no problem. I use this Ollama instance to connect to bunch of tools so it is not Ollama running for sure.

I am running CheshireCat on the same WLS2 instance. So they are local to each other.

![image](https://github.com/cheshire-cat-ai/core/assets/8519469/e1482788-c61d-4555-bb06-4db2855421d0)

![image](https://github.com/cheshire-cat-ai/core/assets/8519469/749d200e-d1e6-4fef-8cef-bb76f1d90cab)

![image](https://github.com/cheshire-cat-ai/core/assets/8519469/290ee6f3-84c5-465d-8b1e-199520716a95)

It complaints that it is not set.

![image](https://github.com/cheshire-cat-ai/core/assets/8519469/6a611bcd-f120-41d8-a268-c39811eb6b2d)

**Comment by nicola-corbellini** [comment]
ollama outside the cat's docker-compose, isn't it?
I think you should change from localhost to your machine ip address

**Comment by valentimarco** [comment]
you cannot use localhost or 127.0.0.1 inside a docker container to talk to the outside, you must use the machine ip.
If you want all-in-one there is the [local repo](https://github.com/cheshire-cat-ai/local-cat) that all already configurated

**Comment by gerroon** [comment]
CheshireCat  is running inside the same WSL1 Docker instance. I will try external URL  suggestion.

**Comment by gerroon** [comment]
Ok I have local ollama connected but some other issue is causing another havoc :(

![image](https://github.com/cheshire-cat-ai/core/assets/8519469/de6c3f97-08ee-477b-9a0b-05b6a116c640)

not sure if these are related.

```
[notice] To update, run: pip install --upgrade pip                                                                                                                                                                                                                                INFO:     10.2.0.18:53157 - "PUT /llm/settings/LLMOllamaConfig HTTP/1.1" 200 OK                                                                                                                                                                                                   INFO:     10.2.0.18:53174 - "GET /admin/ HTTP/1.1" 200 OK                                                                                                                                                                                                                         INFO:     10.2.0.18:53176 - "GET /embedder/settings/ HTTP/1.1" 500 Internal Server Error                                                                                                                                                                                          ERROR:    Exception in ASGI application                                                                                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                                                                                                  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi                                                                                                                                                                      result = await app(  # type: ignore[func-returns-value]                                                                                                                                                                                                                         File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__                                                                                                                                                                            return await self.app(scope, receive, send)                                                                                                                                                                                                                                     File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__                                                                                                                                                                                       await super().__call__(scope, receive, send)                                                                                                                                                                                                                                    File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__                                                                                                                                                                                     await self.middleware_stack(scope, receive, send)                                                                                                                                                                                                                               File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__                                                                                                                                                                                raise exc                                                                                                                                                                                                                                                                       File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__                                                                                                                                                                                await self.app(scope, receive, _send)                                                                                                                                                                                                                                           File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__                                                                                                                                                                                   await self.app(scope, receive, send)                                                                                                                                                                                                                                            File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__                                                                                                                                                                             raise exc                                                                                                                                                                                                                                                                       File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__                                                                                                                                                                             await self.app(scope, receive, sender)                                                                                                                                                                                                                                          File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__                                                                                                                                                                           raise e                                                                                                                                                                                                                                                                         File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__                                                                                                                                                                           await self.app(scope, receive, send)                                                                                                                                                                                                                                            File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__                                                                                                                                                                                          await route.handle(scope, receive, send)                                                                                                                                                                                                                                        File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle                                                                                                                                                                                            await self.app(scope, receive, send)                                                                                                                                                                                                                                            File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app                                                                                                                                                                                                response = await func(request)                                                                                                                                                                                                                                                  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app                                                                                                                                                                                                 raw_response = await run_endpoint_function(                                                                                                                                                                                                                                     File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function                                                                                                                                                                               return await run_in_threadpool(dependant.call, **values)                                                                                                                                                                                                                        File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool                                                                                                                                                                              return await anyio.to_thread.run_sync(func, *args)                                                                                                                                                                                                                              File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync                                                                                                                                                                                             return await get_asynclib().run_sync_in_worker_thread(                                                                                                                                                                                                                          File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread                                                                                                                                                                  return await future                                                                                                                                                                                                                                                             File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run                                                                                                                                                                                        result = context.run(func, *args)                                                                                                                                                                                                                                               File "/app/cat/routes/embedder.py", line 38, in get_embedders_settings                                                                                                                                                                                                              saved_settings = crud.get_settings_by_category(category=EMBEDDER_CATEGORY)                                                                                                                                                                                                      File "/app/cat/db/crud.py", line 17, in get_settings_by_category                                                                                                                                                                                                                    return get_db().search(query.category == category)                                                                                                                                                                                                                              File "/usr/local/lib/python3.10/site-packages/tinydb/table.py", line 254, in search                                                                                                                                                                                                 for doc_id, doc in self._read_table().items()                                                                                                                                                                                                                                   File "/usr/local/lib/python3.10/site-packages/tinydb/table.py", line 704, in _read_table                                                                                                                                                                                            tables = self._storage.read()                                                                                                                                                                                                                                                   File "/usr/local/lib/python3.10/site-packages/tinydb/storages.py", line 136, in read                                                                                                                                                                                                return json.load(self._handle)                                                                                                                                                                                                                                                  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load                                                                                                                                                                                                                return loads(fp.read(),                                                                                                                                                                                                                                                         File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads                                                                                                                                                                                                               return _default_decoder.decode(s)                                                                                                                                                                                                                                               File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode                                                                                                                                                                                                               obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                                                                                                                                               File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode                                                                                                                                                                                                           raise JSONDecodeError("Expecting value", s, err.value) from None                                                                                                                                                                                                              json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                               

```

**Comment by nicola-corbellini** [comment]
Delete the Cat and start from scratch
