### ISSUE TITLE
[BUG] querying after uploading multiple large text files results in error '>=' not supported between instances of 'ValueError' and 'int'

### ISSUE THREAD

**Issue by adamakhtar** [cheshire-cat-ai/core#733]
**Describe the bug**

I've uploaded 6 books in plain text. I try to ask a question but I am greeted with the following error in the client "'>=' not supported between instances of 'ValueError' and 'int'".

Interestingly uploading only one or two books does not result in this error. Is this related to too much information being placed into context?

I have no plugins installed and am using OpenAI ChatGPT model and OpenAI Embedder with text-embedding-ada-002. 

<details>
  <summary>Full error log</summary>
  
```
INFO   cat.looking_glass.stray_cat.StrayCat.__call__::233
{
    "text": "What is a constructor",
    "user_id": "user"
}
[2024-03-03 09:16:25.227] INFO   cat.looking_glass.stray_cat.StrayCat.recall_relevant_memories_to_working_memory::123
"Recall query: \"What is a constructor\""
[2024-03-03 09:16:25.961] ERROR  cat.looking_glass.stray_cat.StrayCat.__call__::254
ValueError('operands could not be broadcast together with shapes (747,) (746,) ')
[2024-03-03 09:16:26.049] ERROR  cat.routes.websocket..websocket_endpoint::81
TypeError("'>=' not supported between instances of 'ValueError' and 'int'")
Traceback (most recent call last):
  File "/app/cat/looking_glass/stray_cat.py", line 252, in __call__
    self.recall_relevant_memories_to_working_memory()
  File "/app/cat/looking_glass/stray_cat.py", line 172, in recall_relevant_memories_to_working_memory
    memories = vector_memory.recall_memories_from_embedding(**config)
  File "/app/cat/memory/vector_memory_collection.py", line 231, in recall_memories_from_embedding
    memories = self.client.search(
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 343, in search
    return self._client.search(
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/local/qdrant_local.py", line 186, in search
    return collection.search(
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/local/local_collection.py", line 437, in search
    mask = payload_mask & ~self.deleted & ~self.deleted_per_vector[name]
ValueError: operands could not be broadcast together with shapes (747,) (746,)
  File "/usr/local/lib/python3.10/site-packages/qdrant_client/local/qdrant_local.py", line 186, in search
    return collection.search(

Traceback (most recent call last):
  File "/app/cat/routes/websocket.py", line 72, in websocket_endpoint
    await asyncio.gather(
  File "/app/cat/routes/websocket.py", line 24, in receive_message
    cat_message = await run_in_threadpool(stray, user_message)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/cat/looking_glass/stray_cat.py", line 255, in __call__
    traceback.print_exc(e)
  File "/usr/local/lib/python3.10/traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/local/lib/python3.10/traceback.py", line 119, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "/usr/local/lib/python3.10/traceback.py", line 502, in __init__
    self.stack = StackSummary.extract(
  File "/usr/local/lib/python3.10/traceback.py", line 357, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'ValueError' and 'int'
```
</details>

**To Reproduce**
Steps to reproduce the behavior (as exampple`):
1. click "upload document" 
2. choose several large text files
3. ask a question based on the uploded content

**Expected behavior**

It should not show an error and instead answer my question

**Additional context**

Running on M1 Mac.

**Comment by AlessandroSpallina** [comment]
I do not have time now to debug, I'll leave here a note

I have a similar issue running local-cat, I receive "'>=' not supported between instances of 'UnexpectedResponse' and 'int'".
My experience was:
1) upload a single document and wait for uploading to complete (with the summarization plugin turned on)
2) chat and check that everything is ok
3) download and activate a new plugin
at this point, I see the error.

**Comment by adamakhtar** [comment]
@pieroit thank you for the information. I've currently put on hold the project which required uisng Cheshire Cat so won't be able ot try your suggestions. 

However, in case this helps anybody else, I think I did see some errors regarding embeddings and different sizes in my terminal when uploading the texts so that was likely the issue as you mentioned.

**Comment by FabioBaroni** [comment]
I had the same problem apparently while uploading multiple documents. If uploading a file at a time solves the problem I can do it. I deleted metadata.json (as a suggestion I read on Discord) and restarted and the cat works again, but all my embeddings are gone or they are still stored and can be retrieved? (it was a test installation, so no problem if I had data loss, but I'd like to understand better how it works).

**Comment by AlessandroSpallina** [comment]
@FabioBaroni if you set the same embedder as before your embedded content will stay

**Comment by pieroit** [comment]
> I had the same problem apparently while uploading multiple documents. If uploading a file at a time solves the problem I can do it. I deleted metadata.json (as a suggestion I read on Discord) and restarted and the cat works again, but all my embeddings are gone or they are still stored and can be retrieved? (it was a test installation, so no problem if I had data loss, but I'd like to understand better how it works).

Hi @FabioBaroni,
to have a full fledged vector db use the Qdrant container ([here an example setup](https://github.com/cheshire-cat-ai/local-cat/blob/37fd7639803da0536fa4239fb5827832fea4e3e6/docker-compose.yml#L15)).
The file based version included in core is just for playing around.
Closing this issue ;)
