### ISSUE TITLE
[BUG] - core v1.5.1 traceback when connecting to remote qdrant of version v1.8.x

### ISSUE THREAD

**Issue by zioproto** [cheshire-cat-ai/core#752]
The core container at version 1.5.1 fails with this trace when connecting to the latest v1.8.x qdrant:
```
+ core-54b5845c98-n26kn › core
core-54b5845c98-n26kn core --- Logging error in Loguru Handler #1 ---
core-54b5845c98-n26kn core Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=626694), 'exception': None, 'extra': {}, 'file': (name='embedding.py', path='/usr/local/lib/python3.10/site-packages/fastembed/embedding.py'), 'function': '<module>', 'level': (name='WARNING', no=30, icon='⚠️'), 'line': 7, 'message': 'DefaultEmbedding, FlagEmbedding, JinaEmbedding are deprecated.Use from fastembed import TextEmbedding instead.', 'module': 'embedding', 'name': 'fastembed.embedding', 'process': (id=1, name='MainProcess'), 'thread': (id=140056295745344, name='MainThread'), 'time': datetime(2024, 3, 16, 8, 12, 57, 435596, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}
core-54b5845c98-n26kn core Traceback (most recent call last):
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/loguru/_handler.py", line 184, in emit
core-54b5845c98-n26kn core     formatted = precomputed_format.format_map(formatter_record)
core-54b5845c98-n26kn core KeyError: 'original_name'
core-54b5845c98-n26kn core --- End of logging error ---
core-54b5845c98-n26kn core INFO:     Started server process [1]
core-54b5845c98-n26kn core INFO:     Waiting for application startup.
core-54b5845c98-n26kn core [2024-03-16 08:13:00.330] INFO   cat.mad_hatter.mad_hatter.MadHatter.find_plugins::102
core-54b5845c98-n26kn core "ACTIVE PLUGINS:"
core-54b5845c98-n26kn core [2024-03-16 08:13:00.332] INFO   cat.mad_hatter.mad_hatter.MadHatter.find_plugins::103
core-54b5845c98-n26kn core [
core-54b5845c98-n26kn core     "core_plugin"
core-54b5845c98-n26kn core ]
core-54b5845c98-n26kn core [2024-03-16 08:13:00.334] DEBUG  cat.mad_hatter.plugin.Plugin._load_decorated_functions::287
core-54b5845c98-n26kn core "Import module cat.mad_hatter.core_plugin.plugin_events"
core-54b5845c98-n26kn core [2024-03-16 08:13:00.337] DEBUG  cat.mad_hatter.plugin.Plugin._load_decorated_functions::287
core-54b5845c98-n26kn core "Import module cat.mad_hatter.core_plugin.tools"
core-54b5845c98-n26kn core [2024-03-16 08:13:00.339] DEBUG  cat.mad_hatter.plugin.Plugin._load_decorated_functions::287
core-54b5845c98-n26kn core "Import module cat.mad_hatter.core_plugin.hooks.language"
core-54b5845c98-n26kn core [2024-03-16 08:13:00.342] DEBUG  cat.mad_hatter.plugin.Plugin._load_decorated_functions::287
core-54b5845c98-n26kn core "Import module cat.mad_hatter.core_plugin.hooks.prompt"
core-54b5845c98-n26kn core [2024-03-16 08:13:00.344] DEBUG  cat.mad_hatter.plugin.Plugin._load_decorated_functions::287
core-54b5845c98-n26kn core "Import module cat.mad_hatter.core_plugin.hooks.flow"
core-54b5845c98-n26kn core [2024-03-16 08:13:00.346] DEBUG  cat.mad_hatter.plugin.Plugin._load_decorated_functions::287
core-54b5845c98-n26kn core "Import module cat.mad_hatter.core_plugin.hooks.rabbithole"
core-54b5845c98-n26kn core [2024-03-16 08:13:00.348] DEBUG  cat.mad_hatter.plugin.Plugin._load_decorated_functions::287
core-54b5845c98-n26kn core "Import module cat.mad_hatter.core_plugin.hooks.agent"
core-54b5845c98-n26kn core [2024-03-16 08:13:00.350] DEBUG  cat.mad_hatter.mad_hatter.MadHatter.execute_hook::244
core-54b5845c98-n26kn core "Executing core_plugin::before_cat_bootstrap with priotrity 0"
core-54b5845c98-n26kn core [2024-03-16 08:13:00.376] INFO   cat.memory.vector_memory_collection.VectorMemoryCollection.create_db_collection_if_not_exists::94
core-54b5845c98-n26kn core "Collection 'episodic' already present in vector store"
core-54b5845c98-n26kn core ERROR:    Traceback (most recent call last):
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 94, in send
core-54b5845c98-n26kn core     return parse_as_type(response.json(), type_)
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 213, in parse_as_type
core-54b5845c98-n26kn core     return model_type(obj=obj).obj
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
core-54b5845c98-n26kn core     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
core-54b5845c98-n26kn core pydantic_core._pydantic_core.ValidationError: 1 validation error for ParsingModel[InlineResponse2005] (for parse_as_type)
core-54b5845c98-n26kn core obj.result.config.optimizer_config.max_optimization_threads
core-54b5845c98-n26kn core   Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
core-54b5845c98-n26kn core     For further information visit https://errors.pydantic.dev/2.4/v/int_type
core-54b5845c98-n26kn core
core-54b5845c98-n26kn core During handling of the above exception, another exception occurred:
core-54b5845c98-n26kn core
core-54b5845c98-n26kn core Traceback (most recent call last):
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
core-54b5845c98-n26kn core     async with self.lifespan_context(app) as maybe_state:
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
core-54b5845c98-n26kn core     return await anext(self.gen)
core-54b5845c98-n26kn core   File "/app/core/./cat/main.py", line 29, in lifespan
core-54b5845c98-n26kn core     app.state.ccat = CheshireCat()
core-54b5845c98-n26kn core   File "/app/core/./cat/utils.py", line 150, in getinstance
core-54b5845c98-n26kn core     cls.instances[class_] = class_(*args, **kwargs)
core-54b5845c98-n26kn core   File "/app/core/./cat/looking_glass/cheshire_cat.py", line 67, in __init__
core-54b5845c98-n26kn core     self.load_memory()
core-54b5845c98-n26kn core   File "/app/core/./cat/looking_glass/cheshire_cat.py", line 257, in load_memory
core-54b5845c98-n26kn core     self.memory = LongTermMemory(vector_memory_config=vector_memory_config)
core-54b5845c98-n26kn core   File "/app/core/./cat/memory/long_term_memory.py", line 17, in __init__
core-54b5845c98-n26kn core     self.vectors = VectorMemory(**vector_memory_config)
core-54b5845c98-n26kn core   File "/app/core/./cat/memory/vector_memory.py", line 37, in __init__
core-54b5845c98-n26kn core     collection = VectorMemoryCollection(
core-54b5845c98-n26kn core   File "/app/core/./cat/memory/vector_memory_collection.py", line 51, in __init__
core-54b5845c98-n26kn core     self.check_embedding_size()
core-54b5845c98-n26kn core   File "/app/core/./cat/memory/vector_memory_collection.py", line 62, in check_embedding_size
core-54b5845c98-n26kn core     self.client.get_collection(self.collection_name).config.params.vectors.size
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1530, in get_collection
core-54b5845c98-n26kn core     return self._client.get_collection(collection_name=collection_name, **kwargs)
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 1963, in get_collection
core-54b5845c98-n26kn core     result: Optional[types.CollectionInfo] = self.http.collections_api.get_collection(
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 1262, in get_collection
core-54b5845c98-n26kn core     return self._build_for_get_collection(
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 377, in _build_for_get_collection
core-54b5845c98-n26kn core     return self.api_client.request(
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
core-54b5845c98-n26kn core     return self.send(request, type_)
core-54b5845c98-n26kn core   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 96, in send
core-54b5845c98-n26kn core     raise ResponseHandlingException(e)
core-54b5845c98-n26kn core qdrant_client.http.exceptions.ResponseHandlingException: 1 validation error for ParsingModel[InlineResponse2005] (for parse_as_type)
core-54b5845c98-n26kn core obj.result.config.optimizer_config.max_optimization_threads
core-54b5845c98-n26kn core   Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
core-54b5845c98-n26kn core     For further information visit https://errors.pydantic.dev/2.4/v/int_type
core-54b5845c98-n26kn core
core-54b5845c98-n26kn core ERROR:    Application startup failed. Exiting.
```

**workaround**: Use qdrant v1.7.2 to fix the issue.

**What is actionable ?**:
document what version of qdrant is required to run the cat.

**Comment by bositalia** [comment]
I find same problem, and i find how bypass this problem temporaly.
The problem is in  \local-cat\cat\long_term_memory\vector\collections\episodic\config.json file.
Missing parameter in setup: 
{"params":{"vectors":{"size":1024,"distance":"Cosine"},"shard_number":1,"replication_factor":1,"write_consistency_factor":1,"on_disk_payload":true},"hnsw_config":{"m":16,"ef_construct":100,"full_scan_threshold":10000,"max_indexing_threads":0,"on_disk":false},"optimizer_config":{"deleted_threshold":0.2,"vacuum_min_vector_number":1000,"default_segment_number":0,"max_segment_size":null,"memmap_threshold":20000,"indexing_threshold":20000,"flush_interval_sec":5,

**"max_optimization_threads":null},**    <<< the null not accepted. If you change to 1 or more, work fine.

i changed to "max_optimization_threads":**1**},    <<< now start.

i changed to "max_optimization_threads":**4**},    <<< in my case work very fast, test in your sistem.

"wal_config":{"wal_capacity_mb":32,"wal_segments_ahead":0},"quantization_config":{"scalar":{"type":"int8","quantile":0.95,"always_ram":true}}}
I find 2 week ago this problem but i wait to write, now qdrant version ready is 1.7.1.
After changing parameters, restart containers.
