### ISSUE TITLE
[BUG] event loop is already running.

### ISSUE THREAD

**Issue by ElioErrico** [cheshire-cat-ai/core#978]
**event loop is already running.**

Hello guys,
sometimes the cat broke doing nothing in particular.
When I refresh i get this error,
in order to solve in I have to do docker compose up and docker compose down
The problem could be my plugin or sometimes happens also to you?

```
cheshire_cat_core  | INFO:     172.20.0.1:34920 - "GET /plugins/ HTTP/1.1" 200 OK
cheshire_cat_core  | [2024-11-19 20:26:06.864] ERROR  cat.looking_glass.stray_cat.StrayCat.run::460
cheshire_cat_core  | RuntimeError('this event loop is already running.')
cheshire_cat_core  | Traceback (most recent call last):
cheshire_cat_core  |   File "/app/cat/looking_glass/stray_cat.py", line 455, in run
cheshire_cat_core  |     cat_message = self.loop.run_until_complete(self.__call__(user_message_json))
cheshire_cat_core  |   File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
cheshire_cat_core  |   File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
cheshire_cat_core  |   File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
cheshire_cat_core  |   File "uvloop/loop.pyx", line 518, in uvloop.loop.Loop._run
cheshire_cat_core  | RuntimeError: this event loop is already running.
```

**Comment by alfredotoselli** [comment]
Can you reproduce the error without custom plugins?

**Comment by alfredotoselli** [comment]
> Difficult to say... Just sometimes happens. I will try and I will let you know. Never happened to you?

Nope

**Comment by pieroit** [comment]
Cannot replicate the issue, closing until a systematic way to do it is posted
